namespace IkinciElKitapProjesi.Helpers
{
    public static class TurkiyeYerlesimBirimleri
    {
        public static Dictionary<string, List<string>> IllerVeIlceler = new()
        {
            { "İstanbul", new List<string> { "Adalar", "Arnavutköy", "Ataşehir", "Avcılar", "Bağcılar", "Bahçelievler", "Bakırköy", "Başakşehir", "Bayrampaşa", "Beşiktaş", "Beykoz", "Beylikdüzü", "Beyoğlu", "Büyükçekmece", "Çatalca", "Çekmeköy", "Esenler", "Esenyurt", "Eyüpsultan", "Fatih", "Gaziosmanpaşa", "Güngören", "Kadıköy", "Kağıthane", "Kartal", "Küçükçekmece", "Maltepe", "Pendik", "Sancaktepe", "Sarıyer", "Silivri", "Sultanbeyli", "Sultangazi", "Şile", "Şişli", "Tuzla", "Ümraniye", "Üsküdar", "Zeytinburnu" } },
            { "Ankara", new List<string> { "Akyurt", "Altındağ", "Ayaş", "Bala", "Beypazarı", "Çamlıdere", "Çankaya", "Çubuk", "Elmadağ", "Etimesgut", "Evren", "Gölbaşı", "Güdül", "Haymana", "Kalecik", "Kazan", "Keçiören", "Kızılcahamam", "Mamak", "Nallıhan", "Polatlı", "Pursaklar", "Sincan", "Şereflikoçhisar", "Yenimahalle" } },
            { "İzmir", new List<string> { "Aliağa", "Balçova", "Bayındır", "Bayraklı", "Bergama", "Beydağ", "Bornova", "Buca", "Çeşme", "Çiğli", "Dikili", "Foça", "Gaziemir", "Güzelbahçe", "Karabağlar", "Karaburun", "Karşıyaka", "Kemalpaşa", "Kınık", "Kiraz", "Konak", "Menderes", "Menemen", "Narlıdere", "Ödemiş", "Seferihisar", "Selçuk", "Tire", "Torbalı", "Urla" } },
            { "Bursa", new List<string> { "Büyükorhan", "Gemlik", "Gürsu", "Harmancık", "İnegöl", "İznik", "Karacabey", "Keles", "Kestel", "Mudanya", "Mustafakemalpaşa", "Nilüfer", "Orhaneli", "Orhangazi", "Osmangazi", "Yenişehir", "Yıldırım" } },
            { "Antalya", new List<string> { "Akseki", "Aksu", "Alanya", "Demre", "Döşemealtı", "Elmalı", "Finike", "Gazipaşa", "Gündoğmuş", "İbradı", "Kaş", "Kemer", "Kepez", "Konyaaltı", "Korkuteli", "Kumluca", "Manavgat", "Muratpaşa", "Serik" } },
            { "Adana", new List<string> { "Aladağ", "Ceyhan", "Çukurova", "Feke", "İmamoğlu", "Karaisalı", "Karataş", "Kozan", "Pozantı", "Saimbeyli", "Sarıçam", "Seyhan", "Tufanbeyli", "Yumurtalık", "Yüreğir" } },
            { "Konya", new List<string> { "Ahırlı", "Akören", "Akşehir", "Altınekin", "Beyşehir", "Bozkır", "Cihanbeyli", "Çeltik", "Çumra", "Derbent", "Derebucak", "Doğanhisar", "Emirgazi", "Ereğli", "Güneysınır", "Hadim", "Halkapınar", "Hüyük", "Ilgın", "Kadınhanı", "Karapınar", "Karatay", "Kulu", "Meram", "Sarayönü", "Selçuklu", "Seydişehir", "Taşkent", "Tuzlukçu", "Yalıhüyük", "Yunak" } },
            { "Gaziantep", new List<string> { "Araban", "İslahiye", "Karkamış", "Nizip", "Nurdağı", "Oğuzeli", "Şahinbey", "Şehitkamil", "Yavuzeli" } },
            { "Mersin", new List<string> { "Akdeniz", "Anamur", "Aydıncık", "Bozyazı", "Çamlıyayla", "Erdemli", "Gülnar", "Mezitli", "Mut", "Silifke", "Tarsus", "Toroslar", "Yenişehir" } },
            { "Diyarbakır", new List<string> { "Bağlar", "Bismil", "Çermik", "Çınar", "Çüngüş", "Dicle", "Eğil", "Ergani", "Hani", "Hazro", "Kayapınar", "Kocaköy", "Kulp", "Lice", "Silvan", "Sur", "Yenişehir" } }
        };

        public static Dictionary<string, List<string>> Mahalleler = new()
        {
            { "Adalar", new List<string> { "Büyükada", "Heybeliada", "Burgazada", "Kınalıada", "Sedefadası", "Sivriada", "Yassıada", "Tavşanadası" } },
            { "Arnavutköy", new List<string> { "Adnan Menderes", "Anadolu", "Arnavutköy Merkez", "Atatürk", "Baklalı", "Balaban", "Boğazköy", "Bolluca", "Dursunköy", "Fatih", "Hacımaşlı", "Haraççı", "Hastane", "Karaburun", "Karlıbayır", "Mavigöl", "Mevlana", "Ömerli", "Sazlıbosna", "Taşoluk", "Tayakadın", "Terkos", "Yassıören", "Yavuzselim" } },
            { "Ataşehir", new List<string> { "Atatürk", "Barbaros", "Esatpaşa", "Ferhatpaşa", "Fetih", "İçerenköy", "İnönü", "Kazımkarabekir", "Kayışdağı", "Küçükbakkalköy", "Mevlana", "Mimarsinan", "Mustafa Kemal", "Örnek", "Yeniçamlıca", "Yenisahra" } },
            { "Avcılar", new List<string> { "Ambarlı", "Cihangir", "Denizköşkler", "Firuzköy", "Gümüşpala", "Merkez", "Mustafa Kemalpaşa", "Tahtakale", "Üniversite", "Yeşilkent" } },
            { "Bağcılar", new List<string> { "Bağlar", "Barbaros", "Çınar", "Demirkapı", "Evren", "Fatih", "Fevziçakmak", "Göztepe", "Güneşli", "Hürriyet", "İnönü", "Kazımkarabekir", "Kirazlı", "Mahmutbey", "Mareşal Fevziçakmak", "Mevlana", "Sancaktepe", "Yavuzselim", "Yenigün", "Yenimahalle" } },
            { "Bahçelievler", new List<string> { "Adnan Kahveci", "Bahçelievler", "Cumhuriyet", "Çobançeşme", "Fenerbahçe", "Hürriyet", "Kocasinan", "Seymen", "Sokullu Mehmet Paşa", "Soğanlı", "Şirinevler", "Yenibosna", "Zafer" } },
            { "Bakırköy", new List<string> { "Ataköy", "Basınköy", "Cevizlik", "Kartaltepe", "Osmaniye", "Sakızağacı", "Şenlikköy", "Yenimahalle", "Yeşilköy", "Yeşilyurt", "Zeytinlik" } },
            { "Başakşehir", new List<string> { "Altınşehir", "Bahçeşehir", "Başak", "Başakşehir", "Esenkent", "Güvercintepe", "Kayabaşı", "Şahintepe", "Ziya Gökalp" } },
            { "Bayrampaşa", new List<string> { "Altıntepsi", "Cevatpaşa", "İsmetpaşa", "Kartaltepe", "Muratpaşa", "Ortamahalle", "Vatan", "Yenidoğan" } },
            { "Beşiktaş", new List<string> { "Abbasağa", "Akat", "Arnavutköy", "Bebek", "Etiler", "Gayrettepe", "Levent", "Ortaköy", "Sinanpaşa", "Türkali", "Vişnezade", "Yıldız" } },
            { "Beykoz", new List<string> { "Acarlar", "Anadolufeneri", "Baklacı", "Beykoz", "Cumhuriyet", "Çamlıbahçe", "Çiğdem", "Çubuklu", "Fatih", "Göksu", "Gümüşsuyu", "Hisarüstü", "İncirköy", "Kanlıca", "Kavacık", "Küçüksu", "Mahmutşevketpaşa", "Merkez", "Ortaçeşme", "Paşabahçe", "Rüzgarlı", "Soğuksu", "Tokatköy", "Yalıköy", "Yavuzselim" } },
            { "Beylikdüzü", new List<string> { "Adnan Kahveci", "Barış", "Büyükbakkalköy", "Cumhuriyet", "Dereağzı", "Gürpınar", "Kavaklı", "Marmara", "Sahil", "Yakuplu" } },
            { "Beyoğlu", new List<string> { "Bedrettin", "Bereketzade", "Bostan", "Bülbül", "Camiikebir", "Çatma Mescit", "Çukur", "Emekyemez", "Evliya Çelebi", "Fetihtepe", "Hacıahmet", "Hacımimi", "Halıcıoğlu", "Hüseyinağa", "Kadımehmetefendi", "Kalyoncukulluk", "Kamerhatun", "Karaahmetpaşa", "Karabaş", "Karagümrük", "Karaköy", "Kasımpaşa", "Kemankeş", "Kılıçalipaşa", "Kulaksız", "Kuloğlu", "Küçükpiyale", "Müeyyetzade", "Ömeravni", "Örnektepe", "Piripaşa", "Piyalepaşa", "Pürtelaş", "Sütlüce", "Şahkulu", "Şehitmuhtar", "Tomtom", "Yahya Kahya", "Yenişehir" } },
            { "Büyükçekmece", new List<string> { "Ahmediye", "Alkent", "Atatürk", "Bahçelievler", "Beylikdüzü", "Cumhuriyet", "Çakmaklı", "Dizdariye", "Esenyurt", "Fatih", "Güzelce", "Hürriyet", "Kale", "Karaağaç", "Kumburgaz", "Mimaroba", "Mimarsinan", "Muratçeşme", "Pınartepe", "Sarıyer", "Sultaniye", "Tepecik", "Yenimahalle" } },
            { "Çatalca", new List<string> { "Binkılıç", "Çanakça", "Çatalca", "Elbasan", "Ferhatpaşa", "Gökçeali", "Gümüşpınar", "Hallaclı", "İhsaniye", "İnceğiz", "Kabakça", "Kaleiçi", "Kestanelik", "Kızılcaali", "Muratbey", "Nakkaş", "Oklalı", "Örcünlü", "Örencik", "Subaşı", "Yalıköy", "Yaylacık", "Yazlık" } },
            { "Çekmeköy", new List<string> { "Alemdar", "Ataşehir", "Cumhuriyet", "Ekşioğlu", "Fevziçakmak", "Hamidiye", "Huzur", "Kirazlıdere", "Mehmet Akif", "Merkez", "Mimar Sinan", "Nişantepe", "Ömerli", "Paşabahçe", "Sarıgazi", "Soğukpınar", "Sultançiftliği", "Şehitler", "Taşdelen", "Yenişehir" } },
            { "Esenler", new List<string> { "Atışalanı", "Birlik", "Çiftehavuzlar", "Davutpaşa", "Fatih", "Havaalanı", "Karabayır", "Kazımkarabekir", "Menderes", "Namık Kemal", "Nenehatun", "Oruçreis", "Talatpaşa", "Turgutreis", "Yavuzselim" } },
            { "Esenyurt", new List<string> { "Akçaburgaz", "Ardıçlı", "Aşıkveysel", "Atatürk", "Bağlarçeşme", "Balıkyolu", "Cumhuriyet", "Çakmaklı", "Dereağzı", "Esenkent", "Fatih", "Gökevler", "Gürpınar", "Hürriyet", "İncirtepe", "İnönü", "Karaburun", "Kıraç", "Kumkapı", "Mehterçeşme", "Mevlana", "Namık Kemal", "Nenehatun", "Örnek", "Pınar", "Piri Reis", "Saadetdere", "Selahaddineyyubi", "Sultaniye", "Şehitler", "Talatpaşa", "Turgutreis", "Ümraniye", "Yenikent", "Yeşilkent", "Yunus" } },
            { "Eyüpsultan", new List<string> { "Ağaçlı", "Akpınar", "Alibeyköy", "Çırçır", "Düğmeciler", "Emniyettepe", "Esentepe", "Eyüp", "Feshane", "Göktürk", "Güzeltepe", "İslambey", "Kemerburgaz", "Mithatpaşa", "Odayeri", "Orta", "Rami Cuma", "Rami Yeni", "Sakızağacı", "Silahtarağa", "Topçular", "Yenidoğan", "Yenimahalle" } },
            { "Fatih", new List<string> { "Aksaray", "Akşemsettin", "Alem", "Ali Kuşçu", "Atikali", "Ayvansaray", "Balabanağa", "Balat", "Bereketzade", "Beyazıt", "Binbirdirek", "Cankurtaran", "Cerrahpaşa", "Demirtaş", "Dervişali", "Eminönü", "Hacı Kadın", "Hasekisultan", "Hırka-i Şerif", "Hobyar", "Hoca Gıyasettin", "Hocapaşa", "Hırka-i Şerif", "Hobyar", "Hoca Gıyasettin", "Hocapaşa", "İskenderpaşa", "Kalenderhane", "Karagümrük", "Katip Kasım", "Kemalpaşa", "Küçük Ayasofya", "Küçük Mustafapaşa", "Mercan", "Mesihpaşa", "Mevlanakapı", "Mihrimah Sultan", "Mimarsinan", "Muhsinehatun", "Nişanca", "Rüstempaşa", "Saraçishak", "Sar Demirci", "Seyyid Ömer", "Silivrikapı", "Sultanahmet", "Sultan Selim", "Süleymaniye", "Şehremini", "Şehsuvar Bey", "Tahtakale", "Taya Hatun", "Topkapı", "Yavuz Sinan", "Yavuz Sultan Selim", "Yedikule", "Zeyrek" } },
            { "Gaziosmanpaşa", new List<string> { "Adnan Menderes", "Arnavutköy", "Atatürk", "Bostancı", "Cumhuriyet", "Fazılpaşa", "Fevziçakmak", "Hürriyet", "İnönü", "Kazımkarabekir", "Mevlana", "Mustafa Kemal", "Nenehatun", "Osmangazi", "Sarıgöl", "Şemsipaşa", "Yenidoğan", "Yenimahalle" } },
            { "Güngören", new List<string> { "Akıncılar", "Aksaray", "Atatürk", "Cumhuriyet", "Fevziçakmak", "Gökalp", "Güneştepe", "Kazımkarabekir", "Mareşal Fevziçakmak", "Sanayi", "Tozkoparan", "Yavuzselim" } },
            { "Kadıköy", new List<string> { "19 Mayıs", "Acıbadem", "Bostancı", "Caddebostan", "Caferağa", "Eğitim", "Erenköy", "Fenerbahçe", "Fikirtepe", "Göztepe", "Hasanpaşa", "Koşuyolu", "Merdivenköy", "Osmanağa", "Rasimpaşa", "Sahrayıcedit", "Suadiye", "Zühtüpaşa" } },
            { "Kağıthane", new List<string> { "Atatürk", "Çağlayan", "Çeliktepe", "Emniyetevler", "Gültepe", "Gürsel", "Hamidiye", "Harmantepe", "Hürriyet", "Mehmet Akif", "Merkez", "Nurtepe", "Ortabayır", "Seyrantepe", "Şirintepe", "Talatpaşa", "Telsizler", "Yahya Kemal", "Yeşilce" } },
            { "Kartal", new List<string> { "Atalar", "Ataşehir", "Cevizli", "Cumhuriyet", "Çavuşoğlu", "Esentepe", "Gülpınar", "Hürriyet", "Karlıktepe", "Kordonboyu", "Orhantepe", "Ortamahalle", "Petrol-İş", "Soğanlık", "Topselvi", "Uğur Mumcu", "Vatan", "Yakacık", "Yalı", "Yenişehir" } },
            { "Küçükçekmece", new List<string> { "Atakent", "Atatürk", "Beşyol", "Cennet", "Cumhuriyet", "Fatih", "Fevziçakmak", "Gazi", "Halkalı", "İnönü", "Kanarya", "Kartaltepe", "Kemalpaşa", "Söğütlüçeşme", "Sultanmurat", "Tepeüstü", "Yarımburgaz", "Yenişehir", "Yeşilova" } },
            { "Maltepe", new List<string> { "Altayçeşme", "Altıntepe", "Aydınevler", "Bağdat", "Başıbüyük", "Büyükbakkalköy", "Cevizli", "Çınar", "Esenkent", "Feyzullah", "Fındıklı", "Girne", "Gülensu", "Gülsuyu", "İdealtepe", "Küçükyalı", "Yalı", "Zümrütevler" } },
            { "Pendik", new List<string> { "Ahmet Yesevi", "Bahçelievler", "Batı", "Çamçeşme", "Çınardere", "Doğu", "Dumlupınar", "Ertuğrulgazi", "Fatih", "Fevziçakmak", "Güllübağlar", "Güzelyalı", "Harmandere", "Kavakpınar", "Kaynarca", "Kurtköy", "Orhangazi", "Orta", "Ramazanoğlu", "Sanayi", "Sapanca", "Sülüntepe", "Şeyhli", "Velibaba", "Yayalar", "Yenişehir", "Yukarıdudullu" } },
            { "Sancaktepe", new List<string> { "Abdurrahmangazi", "Akpınar", "Atatürk", "Emek", "Eyüp Sultan", "Fatih", "Hilal", "İnönü", "Kemal Türkler", "Mevlana", "Osmangazi", "Paşaköy", "Safa", "Sarıgazi", "Veysel Karani", "Yunus Emre" } },
            { "Sarıyer", new List<string> { "Ayazağa", "Baltalimanı", "Büyükdere", "Cumhuriyet", "Çayırbaşı", "Darüşşafaka", "Emirgan", "Ferah", "Ferahevler", "Gümüşdere", "Huzur", "İstinye", "Kazımkarabekir", "Kireçburnu", "Kumköy", "Kuzguncuk", "Maden", "Pınar", "Poligon", "Ptt Evleri", "Reşitpaşa", "Rumelihisarı", "Rumelikavağı", "Sarıyer", "Sultanahmet", "Tarabya", "Uskumruköy", "Yeniköy", "Yenişehir" } },
            { "Silivri", new List<string> { "Alibey", "Alipaşa", "Balaban", "Büyükçavuşlu", "Büyükkılıçlı", "Cumhuriyet", "Çayırdere", "Çeltik", "Değirmenköy", "Fatih", "Fevzipaşa", "Gazitepe", "Gümüşyaka", "Hürriyet", "İsmetpaşa", "Kadıköy", "Kavaklı", "Küçükkılıçlı", "Küçüksinekli", "Mimar Sinan", "Ortaköy", "Piri Mehmet Paşa", "Sayan", "Selimpaşa", "Semizkumlar", "Seymen", "Yeni", "Yolçatı" } },
            { "Sultanbeyli", new List<string> { "Abdurrahmangazi", "Adil", "Ahmet Yesevi", "Akşemsettin", "Ata", "Barış", "Battalgazi", "Fatih", "Hamidiye", "Hasanpaşa", "Mecidiye", "Mehmet Akif", "Mevlana", "Necip Fazıl", "Orhan", "Osman", "Recep Tayyip Erdoğan", "Şemsettin", "Turgut Reis", "Yavuzselim" } },
            { "Sultangazi", new List<string> { "Cebeci", "Cumhuriyet", "Esentepe", "Eski Habipler", "Gazi", "Habibler", "İsmetpaşa", "Malkoçoğlu", "Necip Fazıl", "Sultançiftliği", "Uğur Mumcu", "Yayla", "Yunus Emre" } },
            { "Şile", new List<string> { "Ağva", "Balibey", "Çavuş", "Hacıkasım", "Kumbaba", "Şile Merkez" } },
            { "Şişli", new List<string> { "19 Mayıs", "Bozkurt", "Cumhuriyet", "Duatepe", "Ergenekon", "Esentepe", "Feriköy", "Fulya", "Gülbahar", "Gültepe", "Halaskargazi", "Halide Edip Adıvar", "Halil Rıfat Paşa", "Harbiye", "İnönü", "Kaptanpaşa", "Kuştepe", "Mahmut Şevket Paşa", "Mecidiyeköy", "Merkez", "Mimarsinan", "Muharir", "Nişantaşı", "Pangaltı", "Rumeli", "Sıracevizler", "Teşvikiye", "Yayla" } },
            { "Tuzla", new List<string> { "Akköy", "Anadolu", "Aydınlı", "Aydıntepe", "Cami", "Evliya Çelebi", "Fatih", "İçmeler", "İstasyon", "Mescit", "Mimar Sinan", "Orhanlı", "Postane", "Şifa", "Yayla" } },
            { "Ümraniye", new List<string> { "Adem Yavuz", "Atakent", "Atatürk", "Çakmak", "Çamlık", "Elmalıkent", "Esenevler", "Esenkent", "Esenşehir", "Fatih", "Hekimbaşı", "Ihlamurkuyu", "İnkılap", "Kazımkarabekir", "Madenler", "Namık Kemal", "Necip Fazıl", "Parseller", "Site", "Şerifali", "Tantavi", "Yamanevler" } },
            { "Üsküdar", new List<string> { "Acıbadem", "Ahmediye", "Altunizade", "Aziz Mahmut Hüdayi", "Bahçelievler", "Barbaros", "Beylerbeyi", "Bulgurlu", "Burhaniye", "Cumhuriyet", "Çengelköy", "Ferah", "Fıstıkağacı", "Güzeltepe", "Hacıosman", "Hakimiyet-i Milliye", "Harem", "İcadiye", "İhsaniye", "Kandilli", "Kirazlıtepe", "Kısıklı", "Küçüksu", "Küplüce", "Kuzguncuk", "Mimar Sinan", "Mimarsinan", "Muratreis", "Ortaköy", "Örnek", "Paşalimanı", "Rumelihisarı", "Salacak", "Sultantepe", "Tavşanlı", "Ünalan", "Valide-i Atik", "Yavuztürk", "Zeynep Kamil" } },
            { "Zeytinburnu", new List<string> { "Beştelsiz", "Çırpıcı", "Gökalp", "Kazlıçeşme", "Maltepe", "Merkezefendi", "Nuripaşa", "Seyitnizam", "Sümer", "Telsiz", "Veliefendi", "Yenidoğan", "Yeşiltepe" } }
        };

        public static List<string> GetIller()
        {
            return IllerVeIlceler.Keys.ToList();
        }

        public static List<string> GetIlceler(string il)
        {
            return IllerVeIlceler.ContainsKey(il) ? IllerVeIlceler[il] : new List<string>();
        }

        public static List<string> GetMahalleler(string ilce)
        {
            return Mahalleler.ContainsKey(ilce) ? Mahalleler[ilce] : new List<string>();
        }
    }
} 