// <auto-generated />
using System;
using IkinciElKitapProjesi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IkinciElKitapProjesi.Migrations
{
    [DbContext(typeof(IkinciElKitapDbContext))]
    partial class IkinciElKitapDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IkinciElKitapProjesi.Models.Adres", b =>
                {
                    b.Property<int>("AdresID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AdresID"));

                    b.Property<string>("AdresDetay")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<int?>("KullaniciID1")
                        .HasColumnType("int");

                    b.Property<string>("PostaKodu")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("AdresID");

                    b.HasIndex("KullaniciID");

                    b.HasIndex("KullaniciID1");

                    b.ToTable("Adresler");
                });

            modelBuilder.Entity("IkinciElKitapProjesi.Models.Ilan", b =>
                {
                    b.Property<int>("IlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IlanID"));

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("KitapID")
                        .HasColumnType("int");

                    b.Property<int?>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<string>("ResimYolu")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SaticiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IlanID");

                    b.HasIndex("KitapID");

                    b.HasIndex("KullaniciID");

                    b.HasIndex("SaticiID");

                    b.ToTable("Ilanlar");
                });

            modelBuilder.Entity("IkinciElKitapProjesi.Models.Kart", b =>
                {
                    b.Property<int>("KartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("KartID"));

                    b.Property<string>("CVV")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("KartNumarasi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KartTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<int?>("KullaniciID1")
                        .HasColumnType("int");

                    b.Property<DateTime>("SonKullanmaTarihi")
                        .HasColumnType("datetime(6)");

                    b.HasKey("KartID");

                    b.HasIndex("KullaniciID");

                    b.HasIndex("KullaniciID1");

                    b.ToTable("Kartlar");
                });

            modelBuilder.Entity("IkinciElKitapProjesi.Models.Kategori", b =>
                {
                    b.Property<int>("KategoriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("KategoriID"));

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("KategoriID");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("IkinciElKitapProjesi.Models.Kitap", b =>
                {
                    b.Property<int>("KitapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("KitapID"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("KategoriID")
                        .HasColumnType("int");

                    b.Property<int?>("KategoriID1")
                        .HasColumnType("int");

                    b.Property<string>("Yayinevi")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Yazar")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int?>("Yil")
                        .HasColumnType("int");

                    b.HasKey("KitapID");

                    b.HasIndex("KategoriID");

                    b.HasIndex("KategoriID1");

                    b.ToTable("Kitaplar");
                });

            modelBuilder.Entity("IkinciElKitapProjesi.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("KullaniciID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("KullaniciID");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("IkinciElKitapProjesi.Models.Siparis", b =>
                {
                    b.Property<int>("SiparisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SiparisID"));

                    b.Property<int>("AdresID")
                        .HasColumnType("int");

                    b.Property<int>("AliciID")
                        .HasColumnType("int");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IlanID")
                        .HasColumnType("int");

                    b.Property<int?>("KartID")
                        .HasColumnType("int");

                    b.Property<int?>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<string>("OdemeYontemi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SiparisTarihi")
                        .HasColumnType("datetime(6)");

                    b.HasKey("SiparisID");

                    b.HasIndex("AdresID");

                    b.HasIndex("AliciID");

                    b.HasIndex("IlanID");

                    b.HasIndex("KartID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("IkinciElKitapProjesi.Models.Yorum", b =>
                {
                    b.Property<int>("YorumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("YorumID"));

                    b.Property<int>("KitapID")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<int?>("KullaniciID1")
                        .HasColumnType("int");

                    b.Property<int?>("Puan")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("YorumMetni")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("YorumID");

                    b.HasIndex("KitapID");

                    b.HasIndex("KullaniciID");

                    b.HasIndex("KullaniciID1");

                    b.ToTable("Yorumlar");
                });

            modelBuilder.Entity("IkinciElKitapProjesi.Models.Adres", b =>
                {
                    b.HasOne("IkinciElKitapProjesi.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkinciElKitapProjesi.Models.Kullanici", null)
                        .WithMany("Adresler")
                        .HasForeignKey("KullaniciID1");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("IkinciElKitapProjesi.Models.Ilan", b =>
                {
                    b.HasOne("IkinciElKitapProjesi.Models.Kitap", "Kitap")
                        .WithMany()
                        .HasForeignKey("KitapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkinciElKitapProjesi.Models.Kullanici", null)
                        .WithMany("Ilanlar")
                        .HasForeignKey("KullaniciID");

                    b.HasOne("IkinciElKitapProjesi.Models.Kullanici", "Satici")
                        .WithMany()
                        .HasForeignKey("SaticiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kitap");

                    b.Navigation("Satici");
                });

            modelBuilder.Entity("IkinciElKitapProjesi.Models.Kart", b =>
                {
                    b.HasOne("IkinciElKitapProjesi.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkinciElKitapProjesi.Models.Kullanici", null)
                        .WithMany("Kartlar")
                        .HasForeignKey("KullaniciID1");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("IkinciElKitapProjesi.Models.Kitap", b =>
                {
                    b.HasOne("IkinciElKitapProjesi.Models.Kategori", "Kategori")
                        .WithMany()
                        .HasForeignKey("KategoriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkinciElKitapProjesi.Models.Kategori", null)
                        .WithMany("Kitaplar")
                        .HasForeignKey("KategoriID1");

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("IkinciElKitapProjesi.Models.Siparis", b =>
                {
                    b.HasOne("IkinciElKitapProjesi.Models.Adres", "Adres")
                        .WithMany()
                        .HasForeignKey("AdresID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkinciElKitapProjesi.Models.Kullanici", "Alici")
                        .WithMany()
                        .HasForeignKey("AliciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkinciElKitapProjesi.Models.Ilan", "Ilan")
                        .WithMany()
                        .HasForeignKey("IlanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkinciElKitapProjesi.Models.Kart", "Kart")
                        .WithMany()
                        .HasForeignKey("KartID");

                    b.HasOne("IkinciElKitapProjesi.Models.Kullanici", null)
                        .WithMany("Siparisler")
                        .HasForeignKey("KullaniciID");

                    b.Navigation("Adres");

                    b.Navigation("Alici");

                    b.Navigation("Ilan");

                    b.Navigation("Kart");
                });

            modelBuilder.Entity("IkinciElKitapProjesi.Models.Yorum", b =>
                {
                    b.HasOne("IkinciElKitapProjesi.Models.Kitap", "Kitap")
                        .WithMany()
                        .HasForeignKey("KitapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkinciElKitapProjesi.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkinciElKitapProjesi.Models.Kullanici", null)
                        .WithMany("Yorumlar")
                        .HasForeignKey("KullaniciID1");

                    b.Navigation("Kitap");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("IkinciElKitapProjesi.Models.Kategori", b =>
                {
                    b.Navigation("Kitaplar");
                });

            modelBuilder.Entity("IkinciElKitapProjesi.Models.Kullanici", b =>
                {
                    b.Navigation("Adresler");

                    b.Navigation("Ilanlar");

                    b.Navigation("Kartlar");

                    b.Navigation("Siparisler");

                    b.Navigation("Yorumlar");
                });
#pragma warning restore 612, 618
        }
    }
}
